/**
 * Artifact Component
 *
 * Displays files and artifacts generated by AI with preview, download, and share capabilities.
 *
 * @example
 * ```tsx
 * import { Artifact } from '@/components/ai-sdk';
 *
 * <Artifact
 *   artifact={myArtifact}
 *   variant="default"
 *   onDownload={() => console.log('Download')}
 *   onShare={() => console.log('Share')}
 * />
 * ```
 */

import React, { useState } from 'react';
import { View, Text, Pressable, ScrollView, Alert } from 'react-native';
import { theme } from '../../theme';

// Artifact data structure
export interface Artifact {
  id: string;
  type: 'code' | 'document' | 'image' | 'data' | 'json' | 'markdown' | 'other';
  title: string;
  description?: string;
  content: string;
  language?: string; // For code artifacts (e.g., 'typescript', 'python')
  filename?: string;
  size?: number; // Size in bytes
  mimeType?: string;
  createdAt?: Date;
  metadata?: Record<string, any>;
}

// Props interface
export interface ArtifactProps {
  artifact: Artifact;
  variant?: 'default' | 'compact' | 'minimal';
  showPreview?: boolean;
  previewMaxLines?: number;
  onDownload?: (artifact: Artifact) => void;
  onShare?: (artifact: Artifact) => void;
  onCopy?: (artifact: Artifact) => void;
  onViewFull?: (artifact: Artifact) => void;
  testID?: string;
}

// Helper: Get icon for artifact type
const getArtifactIcon = (type: Artifact['type']): string => {
  switch (type) {
    case 'code':
      return '💻';
    case 'document':
      return '📄';
    case 'image':
      return '🖼️';
    case 'data':
      return '📊';
    case 'json':
      return '📋';
    case 'markdown':
      return '📝';
    case 'other':
    default:
      return '📎';
  }
};

// Helper: Format file size
const formatFileSize = (bytes: number): string => {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
};

// Helper: Get language label
const getLanguageLabel = (language: string): string => {
  const labels: Record<string, string> = {
    typescript: 'TypeScript',
    javascript: 'JavaScript',
    python: 'Python',
    java: 'Java',
    cpp: 'C++',
    csharp: 'C#',
    go: 'Go',
    rust: 'Rust',
    swift: 'Swift',
    kotlin: 'Kotlin',
    ruby: 'Ruby',
    php: 'PHP',
    html: 'HTML',
    css: 'CSS',
    sql: 'SQL',
    json: 'JSON',
    yaml: 'YAML',
    markdown: 'Markdown',
  };
  return labels[language.toLowerCase()] || language;
};

// Helper: Truncate content for preview
const truncateContent = (content: string, maxLines: number): { truncated: string; hasMore: boolean } => {
  const lines = content.split('\n');
  if (lines.length <= maxLines) {
    return { truncated: content, hasMore: false };
  }
  return {
    truncated: lines.slice(0, maxLines).join('\n'),
    hasMore: true,
  };
};

// Helper: Get glass effect values
const getBlurForMaterial = (variant: string): number => {
  switch (variant) {
    case 'thin':
      return 10;
    case 'regular':
      return 20;
    case 'thick':
      return 30;
    default:
      return 20;
  }
};

const opacityToHex = (opacity: number): string => {
  const hex = Math.round(opacity * 255).toString(16).padStart(2, '0');
  return hex.toUpperCase();
};

export const Artifact: React.FC<ArtifactProps> = ({
  artifact,
  variant = 'default',
  showPreview = true,
  previewMaxLines = 10,
  onDownload,
  onShare,
  onCopy,
  onViewFull,
  testID = 'artifact',
}) => {
  const [isExpanded, setIsExpanded] = useState(false);

  const icon = getArtifactIcon(artifact.type);
  const { truncated, hasMore } = truncateContent(artifact.content, previewMaxLines);
  const displayContent = isExpanded ? artifact.content : truncated;

  // Handlers
  const handleDownload = () => {
    if (onDownload) {
      onDownload(artifact);
    } else {
      Alert.alert('Download', `Download ${artifact.title}`);
    }
  };

  const handleShare = () => {
    if (onShare) {
      onShare(artifact);
    } else {
      Alert.alert('Share', `Share ${artifact.title}`);
    }
  };

  const handleCopy = () => {
    if (onCopy) {
      onCopy(artifact);
    } else {
      Alert.alert('Copied', 'Content copied to clipboard');
    }
  };

  const handleViewFull = () => {
    if (onViewFull) {
      onViewFull(artifact);
    } else {
      setIsExpanded(!isExpanded);
    }
  };

  // Minimal variant - simple text display
  if (variant === 'minimal') {
    return (
      <View testID={testID} style={{ padding: theme.spacing.md }}>
        <View style={{ flexDirection: 'row', alignItems: 'center', gap: theme.spacing.sm }}>
          <Text style={{ fontSize: 24 }}>{icon}</Text>
          <View style={{ flex: 1 }}>
            <Text
              style={{
                fontSize: theme.typography.body.fontSize,
                fontWeight: '600',
                color: theme.colors.text.primary,
              }}
            >
              {artifact.title}
            </Text>
            {artifact.description && (
              <Text
                style={{
                  fontSize: theme.typography.caption.fontSize,
                  color: theme.colors.text.secondary,
                  marginTop: 2,
                }}
              >
                {artifact.description}
              </Text>
            )}
          </View>
        </View>
      </View>
    );
  }

  // Compact variant - glass card without preview
  if (variant === 'compact') {
    return (
      <View
        testID={testID}
        style={{
          // Glass effect - thin material
          ...theme.glass.blur(getBlurForMaterial('thin')),
          backgroundColor: `${theme.colors.surface.elevated}${opacityToHex(0.7)}`,
          borderRadius: theme.borderRadius.lg,
          borderWidth: 1,
          borderColor: `${theme.colors.border.default}${opacityToHex(0.3)}`,
          shadowColor: theme.colors.shadow.default,
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.1,
          shadowRadius: 4,
          elevation: 2,
          padding: theme.spacing.md,
          ...theme.glass.compositingGroup,
        }}
      >
        <View style={{ flexDirection: 'row', alignItems: 'center', gap: theme.spacing.sm }}>
          {/* Icon */}
          <View
            style={{
              width: 40,
              height: 40,
              borderRadius: theme.borderRadius.md,
              backgroundColor: `${theme.colors.surface.default}${opacityToHex(0.5)}`,
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            <Text style={{ fontSize: 20 }}>{icon}</Text>
          </View>

          {/* Info */}
          <View style={{ flex: 1 }}>
            <Text
              style={{
                fontSize: theme.typography.body.fontSize,
                fontWeight: '600',
                color: theme.colors.text.primary,
              }}
            >
              {artifact.title}
            </Text>
            <View style={{ flexDirection: 'row', gap: theme.spacing.xs, marginTop: 2 }}>
              {artifact.language && (
                <Text
                  style={{
                    fontSize: theme.typography.caption.fontSize,
                    color: theme.colors.text.secondary,
                  }}
                >
                  {getLanguageLabel(artifact.language)}
                </Text>
              )}
              {artifact.size && (
                <>
                  {artifact.language && (
                    <Text style={{ color: theme.colors.text.tertiary, fontSize: 10 }}>•</Text>
                  )}
                  <Text
                    style={{
                      fontSize: theme.typography.caption.fontSize,
                      color: theme.colors.text.secondary,
                    }}
                  >
                    {formatFileSize(artifact.size)}
                  </Text>
                </>
              )}
            </View>
          </View>

          {/* Actions */}
          <View style={{ flexDirection: 'row', gap: theme.spacing.xs }}>
            <Pressable
              onPress={handleCopy}
              style={({ pressed }) => ({
                width: 36,
                height: 36,
                borderRadius: theme.borderRadius.md,
                backgroundColor: pressed
                  ? `${theme.colors.surface.default}${opacityToHex(0.8)}`
                  : `${theme.colors.surface.default}${opacityToHex(0.5)}`,
                alignItems: 'center',
                justifyContent: 'center',
              })}
            >
              <Text style={{ fontSize: 16 }}>📋</Text>
            </Pressable>
            {onDownload && (
              <Pressable
                onPress={handleDownload}
                style={({ pressed }) => ({
                  width: 36,
                  height: 36,
                  borderRadius: theme.borderRadius.md,
                  backgroundColor: pressed
                    ? `${theme.colors.surface.default}${opacityToHex(0.8)}`
                    : `${theme.colors.surface.default}${opacityToHex(0.5)}`,
                  alignItems: 'center',
                  justifyContent: 'center',
                })}
              >
                <Text style={{ fontSize: 16 }}>⬇️</Text>
              </Pressable>
            )}
          </View>
        </View>
      </View>
    );
  }

  // Default variant - full glass card with preview
  return (
    <View
      testID={testID}
      style={{
        // Glass effect - regular material
        ...theme.glass.blur(getBlurForMaterial('regular')),
        backgroundColor: `${theme.colors.surface.elevated}${opacityToHex(0.8)}`,
        borderRadius: theme.borderRadius.lg,
        borderWidth: 1,
        borderColor: `${theme.colors.border.default}${opacityToHex(0.3)}`,
        shadowColor: theme.colors.shadow.default,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 3,
        overflow: 'hidden',
        ...theme.glass.compositingGroup,
      }}
    >
      {/* Header */}
      <View style={{ padding: theme.spacing.md, borderBottomWidth: 1, borderBottomColor: `${theme.colors.border.default}${opacityToHex(0.2)}` }}>
        <View style={{ flexDirection: 'row', alignItems: 'flex-start', gap: theme.spacing.sm }}>
          {/* Icon */}
          <View
            style={{
              width: 48,
              height: 48,
              borderRadius: theme.borderRadius.md,
              backgroundColor: `${theme.colors.surface.default}${opacityToHex(0.6)}`,
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            <Text style={{ fontSize: 24 }}>{icon}</Text>
          </View>

          {/* Title & Description */}
          <View style={{ flex: 1 }}>
            <Text
              style={{
                fontSize: theme.typography.title3.fontSize,
                fontWeight: '600',
                color: theme.colors.text.primary,
              }}
            >
              {artifact.title}
            </Text>
            {artifact.description && (
              <Text
                style={{
                  fontSize: theme.typography.caption.fontSize,
                  color: theme.colors.text.secondary,
                  marginTop: 4,
                }}
              >
                {artifact.description}
              </Text>
            )}
          </View>
        </View>

        {/* Metadata */}
        <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: theme.spacing.xs, marginTop: theme.spacing.sm }}>
          {artifact.language && (
            <View
              style={{
                paddingHorizontal: theme.spacing.sm,
                paddingVertical: 4,
                borderRadius: theme.borderRadius.sm,
                backgroundColor: `${theme.colors.primary}${opacityToHex(0.15)}`,
              }}
            >
              <Text
                style={{
                  fontSize: theme.typography.caption.fontSize,
                  color: theme.colors.primary,
                  fontWeight: '600',
                }}
              >
                {getLanguageLabel(artifact.language)}
              </Text>
            </View>
          )}
          {artifact.filename && (
            <View
              style={{
                paddingHorizontal: theme.spacing.sm,
                paddingVertical: 4,
                borderRadius: theme.borderRadius.sm,
                backgroundColor: `${theme.colors.surface.default}${opacityToHex(0.5)}`,
              }}
            >
              <Text
                style={{
                  fontSize: theme.typography.caption.fontSize,
                  color: theme.colors.text.secondary,
                }}
              >
                {artifact.filename}
              </Text>
            </View>
          )}
          {artifact.size && (
            <View
              style={{
                paddingHorizontal: theme.spacing.sm,
                paddingVertical: 4,
                borderRadius: theme.borderRadius.sm,
                backgroundColor: `${theme.colors.surface.default}${opacityToHex(0.5)}`,
              }}
            >
              <Text
                style={{
                  fontSize: theme.typography.caption.fontSize,
                  color: theme.colors.text.secondary,
                }}
              >
                {formatFileSize(artifact.size)}
              </Text>
            </View>
          )}
        </View>
      </View>

      {/* Preview Content */}
      {showPreview && (
        <ScrollView
          style={{
            maxHeight: isExpanded ? 400 : 200,
            backgroundColor: `${theme.colors.surface.default}${opacityToHex(0.3)}`,
          }}
          contentContainerStyle={{ padding: theme.spacing.md }}
        >
          <Text
            style={{
              fontFamily: 'monospace',
              fontSize: 12,
              lineHeight: 18,
              color: theme.colors.text.primary,
            }}
          >
            {displayContent}
          </Text>
        </ScrollView>
      )}

      {/* Expand/Collapse Button */}
      {showPreview && hasMore && (
        <Pressable
          onPress={handleViewFull}
          style={({ pressed }) => ({
            padding: theme.spacing.sm,
            backgroundColor: pressed
              ? `${theme.colors.surface.default}${opacityToHex(0.6)}`
              : `${theme.colors.surface.default}${opacityToHex(0.4)}`,
            borderTopWidth: 1,
            borderTopColor: `${theme.colors.border.default}${opacityToHex(0.2)}`,
            alignItems: 'center',
          })}
        >
          <Text
            style={{
              fontSize: theme.typography.caption.fontSize,
              color: theme.colors.primary,
              fontWeight: '600',
            }}
          >
            {isExpanded ? '▲ Show Less' : '▼ Show More'}
          </Text>
        </Pressable>
      )}

      {/* Actions */}
      <View
        style={{
          flexDirection: 'row',
          padding: theme.spacing.md,
          gap: theme.spacing.sm,
          borderTopWidth: 1,
          borderTopColor: `${theme.colors.border.default}${opacityToHex(0.2)}`,
        }}
      >
        <Pressable
          onPress={handleCopy}
          style={({ pressed }) => ({
            flex: 1,
            paddingVertical: theme.spacing.sm,
            borderRadius: theme.borderRadius.md,
            backgroundColor: pressed
              ? `${theme.colors.surface.default}${opacityToHex(0.8)}`
              : `${theme.colors.surface.default}${opacityToHex(0.6)}`,
            alignItems: 'center',
            flexDirection: 'row',
            justifyContent: 'center',
            gap: theme.spacing.xs,
          })}
        >
          <Text style={{ fontSize: 16 }}>📋</Text>
          <Text
            style={{
              fontSize: theme.typography.body.fontSize,
              color: theme.colors.text.primary,
              fontWeight: '600',
            }}
          >
            Copy
          </Text>
        </Pressable>

        {onDownload && (
          <Pressable
            onPress={handleDownload}
            style={({ pressed }) => ({
              flex: 1,
              paddingVertical: theme.spacing.sm,
              borderRadius: theme.borderRadius.md,
              backgroundColor: pressed
                ? `${theme.colors.primary}${opacityToHex(0.9)}`
                : theme.colors.primary,
              alignItems: 'center',
              flexDirection: 'row',
              justifyContent: 'center',
              gap: theme.spacing.xs,
            })}
          >
            <Text style={{ fontSize: 16 }}>⬇️</Text>
            <Text
              style={{
                fontSize: theme.typography.body.fontSize,
                color: '#FFFFFF',
                fontWeight: '600',
              }}
            >
              Download
            </Text>
          </Pressable>
        )}

        {onShare && (
          <Pressable
            onPress={handleShare}
            style={({ pressed }) => ({
              paddingHorizontal: theme.spacing.md,
              paddingVertical: theme.spacing.sm,
              borderRadius: theme.borderRadius.md,
              backgroundColor: pressed
                ? `${theme.colors.surface.default}${opacityToHex(0.8)}`
                : `${theme.colors.surface.default}${opacityToHex(0.6)}`,
              alignItems: 'center',
              justifyContent: 'center',
            })}
          >
            <Text style={{ fontSize: 18 }}>↗️</Text>
          </Pressable>
        )}
      </View>
    </View>
  );
};

// Example artifacts for testing
export const exampleArtifacts: Artifact[] = [
  {
    id: '1',
    type: 'code',
    title: 'UserAuthentication.ts',
    description: 'TypeScript authentication service with JWT support',
    language: 'typescript',
    filename: 'UserAuthentication.ts',
    size: 2458,
    mimeType: 'text/typescript',
    content: `import { hash, compare } from 'bcrypt';
import jwt from 'jsonwebtoken';

interface User {
  id: string;
  email: string;
  password: string;
}

class AuthService {
  private secret = process.env.JWT_SECRET || 'default-secret';

  async hashPassword(password: string): Promise<string> {
    return hash(password, 10);
  }

  async verifyPassword(password: string, hash: string): Promise<boolean> {
    return compare(password, hash);
  }

  generateToken(userId: string): string {
    return jwt.sign({ userId }, this.secret, { expiresIn: '7d' });
  }

  verifyToken(token: string): { userId: string } | null {
    try {
      return jwt.verify(token, this.secret) as { userId: string };
    } catch {
      return null;
    }
  }
}

export default new AuthService();`,
    createdAt: new Date(),
  },
  {
    id: '2',
    type: 'json',
    title: 'API Response Data',
    description: 'Sample API response with user data',
    language: 'json',
    filename: 'users.json',
    size: 512,
    mimeType: 'application/json',
    content: `{
  "users": [
    {
      "id": "usr_123",
      "name": "Alice Johnson",
      "email": "alice@example.com",
      "role": "admin",
      "lastLogin": "2025-10-29T10:30:00Z"
    },
    {
      "id": "usr_124",
      "name": "Bob Smith",
      "email": "bob@example.com",
      "role": "user",
      "lastLogin": "2025-10-28T15:45:00Z"
    }
  ],
  "total": 2,
  "page": 1
}`,
    createdAt: new Date(),
  },
  {
    id: '3',
    type: 'document',
    title: 'Project Requirements',
    description: 'Feature specifications and requirements document',
    language: 'markdown',
    filename: 'requirements.md',
    size: 1820,
    mimeType: 'text/markdown',
    content: `# Project Requirements

## Overview
Build a modern mobile application with AI-powered features.

## Core Features
1. User authentication with social login
2. AI chat interface with streaming responses
3. File upload and preview
4. Push notifications
5. Offline mode support

## Technical Requirements
- React Native with TypeScript
- AI SDK integration
- Glass morphism UI design
- iOS and Android support
- Performance: < 2s initial load time

## Timeline
- Phase 1: Authentication (2 weeks)
- Phase 2: AI Chat (3 weeks)
- Phase 3: File Management (2 weeks)
- Phase 4: Testing & Launch (1 week)`,
    createdAt: new Date(),
  },
];
